---
title: "Untitled"
author: "Justin"
date: "2023-08-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```






```{r}


df.sum <- df.qual.exp %>% #filter(`Grant Number` != "H80CS00225") %>% 
  ungroup() %>% 
  #rename(`Grant Number` = Grant.Number, `Surplus as a pct of before dep expenses` = Surplus.as.a.pct.of.after.dep.expenses) %>% 
  #filter(MarketShare < 0.4) %>%  #median(MarketShare, na.rm = TRUE) - 0.25
  #inner_join(df.qual.exp %>% filter(Year == 2015 & Total < 15000) %>% select(`Grant Number`), by = c("Grant Number")) %>%  #& Zips < 1.75 or 7.75
  select(`Grant Number`, Year, ID, Att, Sites, Qcomp, Altmans.Z, Pct.HTN.CNTRL, Total, IMM2yo:DepScrn) %>%
  # inner_join(df.qual.exp %>% filter(Year == 2015) %>%
  #                                           mutate(ZipFilter = ifelse(Total < 12000, 1,
  #                                                              ifelse(Total > 12000, 2, NA))) %>% select(`Grant Number`, ZipFilter), by = c("Grant Number")) %>%
  inner_join(df.qual.exp %>% filter(Year == 2016) %>% #mutate(ZipFilter = ifelse(`Surplus as a pct of before dep expenses` < 2, 1, 2)) %>% 
               select(`Grant Number`, ZipFilter, Pct.NHA:Pct.Children, MCD, COM, MCR), by = c("Grant Number")) %>% 
  select(`Grant Number`, Year, ZipFilter, ID, Att, Sites, Qcomp, Altmans.Z, Pct.HTN.CNTRL, Pct.NHA:Pct.Children, MCD, COM, MCR, Total, IMM2yo:DepScrn) %>% 
  mutate(Tx = ifelse(Year >= Att & Att > 0, 1, 0)) %>% 
  unique() %>% 
  mutate(NewQuality = (CRC + ChildBMI + AdultBMI + Tobac + DepScrn) / 5)

#library(did2s)

did2s(
      data = df.sum , 
      yname = "Altmans.Z", 
      treatment = "Tx",
        first_stage = ~ 0 | ID + Year + Pct.NHA + Pct.NHB + Pct.HL + Pct.LessThan100pctFPL + Pct.FarmWorker + Pct.Homeless + Pct.Children + MCD + MCR + COM, 
        second_stage = ~ i(Tx, ref = FALSE),
        cluster_var = "ID",
      verbose = FALSE
    )


#select(ID, Year, ZipFilter, ID, Att, Sites, Qcomp, Altmans.Z) %>% left_join(df.qual.exp %>% select(ID, Year, Pct.NHA:Pct.Children, MCD, COM, MCR), by = c("ID","Year"))
out.qual <- event_study(data = df.qual.exp %>% filter(ZipFilter == 1), 
  yname = "Altmans.Z", idname = "ID", tname = "Year", gname = "Att", estimator = "all", xformla = ~Pct.NHA + Pct.NHB + Pct.HL + Pct.LessThan100pctFPL + Pct.FarmWorker + Pct.Homeless + Pct.Children + MCD + MCR + COM)

out.qual %>% 
  filter(estimator %notin% c("Borusyak, Jaravel, Spiess (2021)")) %>% 
filter(abs(term) <= 3) %>% 
  ggplot(aes(x = term, y = estimate, color = estimator)) + geom_point(position = position_dodge(0.9)) + geom_errorbar(aes(ymin=estimate-1.96*std.error, ymax=estimate+1.96*std.error), width=.2, position = position_dodge(0.9))  + 
  #facet_wrap(~V1, scales = "free_y", ncol = 3) + 
  theme_tufte_revised() + geom_vline(xintercept=-0.5, color="red", linetype="dashed", alpha=.5) + 
  geom_hline(yintercept=0, color="black", linetype="dashed", alpha=.5) 

```





## Variations


```{r}


did2s(
      data = df.sum %>% left_join(df.spill2 %>% 
  group_by(`Grant Number`, Year) %>% 
  summarise(num = sum((Dist + 1) * Sites), 
         denom = sum(Sites), 
         avgdist = num / denom) %>% 
  filter(Year %in% c(2015, 2019)) %>% 
  pivot_wider(id_cols = `Grant Number`, names_from = Year, values_from = avgdist) %>% 
  mutate(ds = `2019` - `2015`) %>% 
    ungroup() %>% 
    mutate(filt = ifelse(ds > median(ds, na.rm = TRUE), 1, 0)), by = c("Grant Number")) %>% filter(filt == 0),#%>% filter(ZipFilter == 2), 
      yname = "NewQuality", 
      treatment = "Tx",
        first_stage = ~ 0 | ID + Year + Pct.NHA + Pct.NHB + Pct.HL + Pct.LessThan100pctFPL + Pct.FarmWorker + Pct.Homeless + Pct.Children + MCD + MCR + COM, 
        second_stage = ~ i(Tx, ref = FALSE),
        cluster_var = "ID",
      verbose = FALSE
    )




did2s(
      data = df.sum %>% left_join(df.spill2 %>% 
  group_by(`Grant Number`, Year) %>% 
  summarise(num = sum((Dist + 1) * Sites), 
         denom = sum(Sites), 
         avgdist = num / denom) %>% 
    filter(Year == 2016) %>% select(`Grant Number`, avgdist), by = c("Grant Number")) ,#%>% filter(ZipFilter == 2), 
      yname = "NewQuality", 
      treatment = "Tx",
        first_stage = ~ 0 | ID + Year + Pct.NHA + Pct.NHB + Pct.HL + Pct.LessThan100pctFPL + Pct.FarmWorker + Pct.Homeless + Pct.Children + MCD + MCR + COM, 
        second_stage = ~ i(Tx, ref = FALSE) + as.numeric(avgdist / 10) + I(Tx *as.numeric(avgdist / 10)),
        cluster_var = "ID",
      verbose = FALSE
    )



```

